<div class='container' id='main_container'>
<div class="row">
	<div class='row box' id='gallery_div'>
		<div class='span12'>
			<div class="row">
				
				<div class="span8">
					<div class="slider-wrapper theme-default">
			            <div id="slider" class="nivoSlider">
			                <img src="images/napa1.png" alt="" title="Napa 一日游活动" />
			                <!--  
			                <a href="http://dev7studios.com"><img src="images/up.jpg" alt="" title="This is an example of a caption" /></a>
			                -->
			                <img src="images/napa3.png" alt="" title="Napa 一日游活动" />
			                <img src="images/napa4.png" alt="" title="Napa 一日游活动" />
			                <img src="images/napa2.png" alt="" title="" />
			                <img src="images/sonoma1.png" alt="" title="sonama 旅行" />
			                 <img src="images/laketahoe2.jpg" alt="" title="Lake Tahoe 之旅" />
			               
			            </div>
            		</div>
				</div>
				
				<div class="span3">
				<br/>
				<br/>
				<br/>
					<img src="images/dbay_logo1.png" />
				</div>
			</div>
		</div>
	</div>
	
	<div class='row well' id="main_edit_div">
		<div class='span4'>
			<table class='people_tbl'>
			  <tbody>
			    <tr>
			      <td>
			      	<div class="row" style="height: 78px;">
			      		<img src="images/passenger-2.png"/>
			      	</div>
			      	<div  class="row">	
			      		<input type='radio' checked name='people' id="passenger"/>乘客
			      	</div>
			      </td>
			      <td>
			      	<div class="row">
			      		<img src="images/attendee.png"/>
			      	</div>
			      	<div class="row">
			      		<span><input type='radio' name='people' id="attendee"/></span>
			      		<span>参与者</span>
			      	</div>
			      </td>
			    </tr>
			    <tr>
					<td>
						<div class="row">
							<img src="images/driver.png"/>
						</div>
						<div class="row">
						
							<input type='radio' name='people' id="driver"/>
							司机
						
						</div>
					</td>
			      <td>
			      	<div class="row">
			      		<img src="images/planner.png"/>
			      	</div>
			      	<div  class="row">
			      		<input type='radio' name='people' id="planner"/>策划者
			      	</div>
			      	</td>
			    </tr>
			  </tbody>
			</table>
		</div>
		
		<div class='span3'>
			<img src="images/arrow.png" id='single_logo'/>
		</div>
		
		<div class='span4 role_div' id="passenger_div" >
			<div class='span4'>
				<input id="passenger_from_addr" name="passenger_from_addr" type="text" placeholder="起点" class="height28 width100"/>
				<input id="passenger_to_addr" name="passenger_to_addr" type="text" placeholder="终点" class="height28 width100"/>
			</div>
			<div class='span4'>
				<input id="passenger_start_date" name="passenger_start_date" type="text" placeholder="出发日期..." class="height28" onclick="calendar.show(this);">
				<input id="passenger_end_date" name="passenger_end_date" type="text" placeholder="返回日期..." class="height28" onclick="calendar.show(this);">
				<input id="passenger_price" name="passenger_price" type="text" placeholder="价格$/人" class="height28">
				<input id="passenger_people_num" name="passenger_people_num" type="text" placeholder="人数" class="height28">
			</div>
			<div class='span4'>
				<button class="submit btn btn-large btn-primary" id="request_ride">请求行程</button>
			</div>
		</div>
		
		
		<div class='span4 role_div hide	' id="driver_div" >
			<div class='span4'>
				<input id="driver_from_addr" name="driver_from_addr" type="text" placeholder="起点" class="height28 width100"/>
				<input  id="driver_to_addr" name="driver_to_addr" type="text" placeholder="终点" class="height28 width100"/>
			</div>
			<div class='span4'>
				<input id="driver_start_date" name="driver_start_date" type="text" placeholder="出发日期..." class="height28" onclick="calendar.show(this);">
				<input id="driver_end_date" name="driver_end_date" type="text" placeholder="返回日期..." class="height28" onclick="calendar.show(this);">
				<input id="driver_price" name=driver_price type="text" placeholder="价格$/人" class="height28">
				<input id="driver_seat_num" name="driver_seat_num" type="text" placeholder="空座" class="height28">
			</div>
			<div class='span4'>
				<a class="btn btn-large btn-primary" href="#" id='post_ride'>发布行程</a>
			</div>
		</div>
		
		<div class='span3 role_div hide' id="attendee_div" >
			
			<div class='span4'>
				<input id="activity_name" name="activity_name"  type="text" placeholder="活动" class="height28">
				<input id="activity_date" name="activity_date" type="text" placeholder="时间" class="height28" onclick="calendar.show(this);">
				<input id="activity_address" name="activity_address" type="text" placeholder="地点" class="height28">
				<input id="activity_price" name="activity_price" type="text" placeholder="价格$/人" class="height28">
				<input id="activity_people_num" name="activity_people_num" type="text" placeholder="人数" class="height28">
			</div>
			
			<div class='span3'><a class="btn btn-large btn-primary" href="#" id='suggest_activity'>建议活动</a></div>
		</div>
		
		<div class='span3 role_div hide' id="planner_div" >
			<div class='span4'>
				<input type="text" placeholder="活动" class="height28">
				<input type="text" placeholder="时间" class="height28" onclick="calendar.show(this);">
				<input type="text" placeholder="地点" class="height28">
				<input type="text" placeholder="价格$/人" class="height28">
				<input type="text" placeholder="人数" class="height28">
			</div>
			
			<div class='span3'><a class="btn btn-large btn-primary" href="#" id='submit_driver'>发起活动</a></div>
		</div>
		
	</div>
	
	<div class="alert alert-success" id="submit_div">
    			感谢您的提交！
  	</div>
	
	
	<hr>
	<div class='row overwrite_row'>
		<div class='span7 slider_box overwrite_row'>
			<div class="row overwrite_row">
				<h2 class='title2'> 搭车信息 </h2>
			</div>
			<div class=" ride_slide">
				<ul id="slider" class="slider">
					<li><a class="fl" href="#"><img src="images/people.png" width="40px" height="40px" alt="" /></a>
						<div class="row">
							<div class="span3 ride_desc">San Francisco &lt;-&gt; San Jose </div>
							<div class="span2 ride_price">$30/人</div>
						</div>
					</li>
					<li><a class="fl" href="javascript:;"><img src="images/people.png" width="40px" height="40px"  alt="" /></a>
						<div class="row">
							<div class="span3 ride_desc">Davic, CA &lt;-&gt; Lake Tahoe, CA </div>
							<div class="span2 ride_price">$68/人</div>
						</div>
					</li>
					<li><a class="fl" href="javascript:;"><img src="images/people.png" width="40px" height="40px"  alt="" /></a>
						<div class="row">
							<div class="span3 ride_desc">Fremont,CA &lt;-&gt; Gilroy,CA</div>
							<div class="span2 ride_price">$45/人</div>
						</div>
				    </li>
				    <li><a class="fl" href="javascript:;"><img src="images/people.png" width="40px" height="40px"  alt="" /></a>
						<div class="row">
							<div class="span3 ride_desc">SJC &lt;-&gt; San Jose,CA </div>
							<div class="span2 ride_price">$14/人</div>
						</div>
				    </li>
				    <li><a class="fl" href="javascript:;"><img src="images/people.png" width="40px" height="40px"  alt="" /></a>
						<div class="row">
							<div class="span3 ride_desc">Berkeley,CA &lt;-&gt; Vacaville,CA </div>
							<div class="span2 ride_price">$32/人</div>
						</div>
				    </li>
					<li><a class="fl" href="javascript:;"><img src="images/people.png" width="40px" height="40px"  alt="" /></a>
						<div class="row">
							<div class="span3 ride_desc">San Jose,CA &lt;-&gt; SFO </div>
							<div class="span2 ride_price">$25/人</div>
						</div>
					</li>
				</ul>
			</div>
		</div>
		<div class='span5 activity_box'>
			<div class="row overwrite_row">
				<h2 class='title2'> 近期活动 </h2>
			</div>
			<div class='row overwrite_row'>
					<dl>
						<dt>旧金山一日游</dt>
					</dl>
					<dl>
						<dt>Napa Valley Rober Mondavi 酒庄一日游</dt>
					</dl>
					<dl>
						<dt>Monterey-Camel 一日游一站式Door To Door 接送</dt>
					</dl>
					<dl>
						<dt>Berkeley -&gt; Mipitas Great Mall 一站式购物活动 </dt>
					</dl>
					<dl>
						<dt>Muir Woods National Monument 红木国家公园旅行</dt>
					</dl>
					<dl>
						<dt>Stanford Shopping Center 购物活动</dt>
					</dl>
					<dl>
						<dt>Point Reyes National Seashore 包车旅行+摄影</dt>
					</dl>
			</div>
		</div>
		</div>
		
	</div>
</div>

<script type="text/javascript">

$(function(){
msgmove(); 
$(".slider").hover(function(){
$(this).attr("name","hovered"); //鼠标经过设置ul的name值为"hovered"
},function(){
$(this).removeAttr("name");
});
});
function msgmove(){ var isIE=!!window.ActiveXObject;
var isIE6=isIE&&!window.XMLHttpRequest;
if($(".slider li").attr("name") != "hovered"){
//判断ul的name属性是否为"hovered"，决定下面代码块是否运行，以实现鼠标经过暂停滚动。
var height = $(".slider li:last").height();
if(isIE6){
//判断IE6，jQuery的animate动画和opacity透明在一起使用在IE6中会出现中文重影现象，
//所以在ie6中实行透明的禁用。
$(".slider li:last").css({"height":0});
}else{ $(".slider li:last").css({"opacity":0,"height":0});
//列表最后的li透明和高度设置为0 }
$(".slider li:first").before($(".slider li:last"));
//把列表最后的li提升到顶部，实现有限列表项无限循环滚动显示
$(".slider li:first").animate({"height":height},300);
//列表顶部的li高度逐渐变高以把下面的li推下去 if(!isIE6){
$(".slider li:first").animate({"opacity":"1"},300);
//在非IE6浏览器中设置透明淡入效果
}
}
setTimeout("msgmove()",3000);
//设置5秒滚动一次
}

$(window).load(function() {
    $('#slider').nivoSlider();
});
</script>
