
<div class='container' id='main_container'>
<div class="row">
	<div class='row box' id='gallery_div'>
		<div class='span12'>
			<div class="row">
				<div class="span8">
					<div class="slider-wrapper theme-default">
			            <div id="slider" class="nivoSlider">
			                <img src="images/toystory.jpg" alt="" />
			                <a href="http://dev7studios.com"><img src="images/up.jpg" alt="" title="This is an example of a caption" /></a>
			                <img src="images/walle.jpg" alt="" data-transition="slideInLeft" />
			                <img src="images/nemo.jpg" alt="" title="#htmlcaption" />
			            </div>
            		</div>
				</div>
				<div class="span4 box3">Ranking</div>
				
			</div>
		</div>
	</div>
	
	<div class='row well'>
		<div class='span4'>
			<table class='people_tbl'>
			  <tbody>
			    <tr>
			      <td><img src="images/passenger-2.png"/><br/><input type='radio' name='people'/>乘客</td>
			      <td>
			      	<img src="images/attendee.png"/><br/>
			      	<input type='radio' name='people'/>&nbsp;参与者
			      </td>
			    </tr>
			    <tr>
			      <td><img src="images/driver.png"/><br/><input type='radio' name='people'/><label class='people_label'>司机</label></td>
			      <td><img src="images/planner.png"/><br/><input type='radio' name='people'/>策划者</td>
			    </tr>
			  </tbody>
			</table>
		
		</div>
		<div class='span4'>
			
			Image
		</div>
		<div class='span3'>
			<div class='span3'><input type="text" placeholder="起始日期..." class="height28" onclick="calendar.show(this);"></div>
			<div class='span3'><input type="text" placeholder="截止日期..." class="height28" onclick="calendar.show(this);"></div>
			<div class='span3'><input type="text" placeholder="地点..." class="height28"></div>
			<div class='span3'><a class="btn btn-large btn-primary" href="#">查询</a></div>
		</div>
	</div>
	<hr>
	<div class='row'>
		
		<div class='span7 box2'>
			<div class="wp">
				<ul id="slider" class="slider">
					<li><a class="fl" href="javascript:;"><img src="images/people.png" width="40px" height="40px" alt="" /></a>
					<p>入山又恐别倾城  世间安得双全 不负如来不负卿</p>
				    </li>
					<li><a class="fl" href="javascript:;"><img src="images/people.png" width="40px" height="40px"  alt="" /></a>
					<p>第一最好不相见，如此便可不相恋。</p>
					</li>
					<li><a class="fl" href="javascript:;"><img src="images/people.png" width="40px" height="40px"  alt="" /></a>
					<p>那一天 闭目在经殿香雾</p>
				    </li>
					<li><a class="fl" href="javascript:;"><img src="images/people.png" width="40px" height="40px"  alt="" /></a>
					<p> 你见 或者不见我  我就在那里 </p>
				</li>
				</ul>
			</div>
		</div>
		<div class='span5 box3'>
			<div class='row'>
				<dl>
					<dt>情人节</dt>
				</dl>
				<!-- 
				<ul id='activity_list'>
					<li>
						<p class='pull-left'>2月14日 情人节活动</p>
					</li>
					<li>
						<p class='pull-left'>2月14日 情人节活动</p>
					</li>
					<li>
						<p class='pull-left'>Napa 一日游活动</p>
					</li>
					 -->
				</ul>
			</div>
		</div>
		</div>
		
	</div>
</div>

<!--
<div class='outside_div'>
	<div class='inside_div' id='header'>	
		<div id='logo_div'>
			<a href=""><img src="images/logo1.jpg" /></a>
		</div>
		<div id='title_bar_div'>
			<ul class="nav-bar">
				<li><a id='renren_login' class="partner_login" href="#">人人登陆</a></li>
				<li><a class='nav_char' href="#">注册</a></li>
				<li><a class='nav_char' href="#">登陆</a></li>
			</ul>
		</div>
	</div>
</div>
<div class='outside_div'>
	<div class='inside_div box' id='main'>
		<div id='main_top'>
			<div class='float_left box_div' id='search_div'>
				<table>
					<tr>
						<td>起始:</<td><input type='text' id='from_date'></td>
						<td>截止:</<td><input type='text' id='to_date'></td>
						
					</tr>
				</table>
			</div>
			<div class='float_right' id='slide_image_div'>
				图片
			</div>
		</div>
		<div id='main_middle'>
			<input type='text' value='Search' id="search_box"/>
			<a class='link_btn'>信息查询</a>
		</div>
		<div id='main_bottom'>
			<div id='sepr_line'></div>
			<div class="wp">
				<ul id="slider" class="slider">
					<li><a class="fl" href="javascript:;"><img src="http://t1.qlogo.cn/mbloghead/b9127c4ca63961bace88/50" alt="" /></a>
					<p>入山又恐别倾城  世间安得双全 不负如来不负卿</p>
				    </li>
					<li><a class="fl" href="javascript:;"><img src="http://t1.qlogo.cn/mbloghead/b9127c4ca63961bace88/50" alt="" /></a>
					<p>第一最好不相见，如此便可不相恋。</p>
					</li>
					<li><a class="fl" href="javascript:;"><img src="http://t1.qlogo.cn/mbloghead/b9127c4ca63961bace88/50" alt="" /></a>
					<p>那一天 闭目在经殿香雾</p>
				    </li>
					<li><a class="fl" href="javascript:;"><img src="http://t1.qlogo.cn/mbloghead/b9127c4ca63961bace88/50" alt="" /></a>
					<p> 你见 或者不见我  我就在那里 </p>
				</li>
				</ul>
			</div>
			
		</div>
		
	</div>
</div>

-->
<script type="text/javascript">
//$(function() {
//	$( "#from_date" ).datepicker();
//	$( "#from_date" ).datepicker( "option", "dateFormat","yy-mm-dd");
//	$( "#to_date" ).datepicker();
//	$( "#to_date" ).datepicker( "option", "dateFormat","yy-mm-dd");
//});

$(function(){
msgmove(); 
$(".slider").hover(function(){
$(this).attr("name","hovered"); //鼠标经过设置ul的name值为"hovered"
},function(){
$(this).removeAttr("name");
});
});
function msgmove(){ var isIE=!!window.ActiveXObject;
var isIE6=isIE&&!window.XMLHttpRequest;
if($(".slider li").attr("name") != "hovered"){
//判断ul的name属性是否为"hovered"，决定下面代码块是否运行，以实现鼠标经过暂停滚动。
var height = $(".slider li:last").height();
if(isIE6){
//判断IE6，jQuery的animate动画和opacity透明在一起使用在IE6中会出现中文重影现象，
//所以在ie6中实行透明的禁用。
$(".slider li:last").css({"height":0});
}else{ $(".slider li:last").css({"opacity":0,"height":0});
//列表最后的li透明和高度设置为0 }
$(".slider li:first").before($(".slider li:last"));
//把列表最后的li提升到顶部，实现有限列表项无限循环滚动显示
$(".slider li:first").animate({"height":height},300);
//列表顶部的li高度逐渐变高以把下面的li推下去 if(!isIE6){
$(".slider li:first").animate({"opacity":"1"},300);
//在非IE6浏览器中设置透明淡入效果
}
}
setTimeout("msgmove()",3000);
//设置5秒滚动一次
}

$(window).load(function() {
    $('#slider').nivoSlider();
});
</script>
