<html>
<head>
<meta charset="utf-8">

<style>
body
{
	margin:auto;
	background: none repeat scroll 0 0 #F5F5F5;
}
.outside_div{
	//border-bottom: 2px solid #DCDCDC;
	display:block;
}

.inside_div{
	width:960px;
	margin:auto;
}
#header
{
height: 65px;
}

.nav-bar a
{	
	text-decoration:none;
}
ul {
    //list-style: none outside none;
}
.nav-bar  li {
    display: inline;
	color:#2F71EB;
}

.nav_char{
	color:#E04141;
	font-family: "Microsoft Yahei","Helvetica Neue","Luxi Sans","DejaVu Sans",Tahoma,"Hiragino Sans GB",STHeiti !important;
	font-size:12px;
}
#logo_div{
	float:left;
}
#title_bar_div{
	float:right;
}

.partner_login{
	padding: 1px 0 0 18px;
}

.partner_login:hover{
	color:#E04141;
}
#renren_login{
	background: url("images/renren_15.jpg") no-repeat scroll left center transparent;
}

.box{
	background: none repeat scroll 0 0 #FFFefa;
    border-radius: 4px 4px 4px 4px;
    box-shadow: 0 1px 3px rgba(34, 25, 25, 0.2);
	font-size:12px;
	text-align:center;
}

.main {
	position:absolute;
	top:45px;
}
#footer{
	//border-top: 1px solid #DCDCDC;
	width:960px;
	margin:auto;
}
.float_left{
	//float:left;
	
}
.float_right{
	//float:left;
	
}
#search_div{
	width:400px;
}

.box_div{
	border: 1px solid #CCCCCC;
	padding:5px;
	margin:5px;
	font-size:12px;
	font-family	"Helvetica Neue",Helvetica,"Lucida Grande",Arial,sans-serif;
	
}
#main_top{
	width:100%;	
}
#main_middle{
	width:400px;
	margin:auto;
	display:inline;
}

.link_btn{
	background-clip: padding-box;
    background-color: #5BA53C;
    background-image: -moz-linear-gradient(#8ABC6B, #579544);
    border: 1px solid rgba(0, 0, 0, 0.4);
    border-radius: 4px 4px 4px 4px;
    box-shadow: 0 1px 0 rgba(255, 255, 255, 0.5) inset, 0 1px 0 rgba(0, 0, 0, 0.6);
    color: #FFFFFF !important;
    display: inline-block;
    font-size: 15px;
    font-weight: 500;
    height: 24px;
    line-height: 24px;
    margin: 0 1px 1px;
    padding: 0 25px;
    
    right: 0;
    text-align: center;
    text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.5);
    
}

#search_box{
	width:300px;
	height:28px;
}
#main_bottom{
	padding:15px;
}
#sepr_line{
	border-top: 1px dashed #B4B8B7;
	width:100%;
}
.wp {position: relative;width:100%;height:300px;overflow:hidden;margin:auto;background:#fff;}
.slider {position: absolute;width: 100%;padding:0;left:0;top: 0;}
.fl {float:left}
.slider img {display:block; padding: 2px; border: 1px solid #ccc} 
.slider li {padding: 10px 0; border-bottom: 1px dashed #ccc;overflow:hidden;width:100%}
.slider p {font-size: 12px;margin:0;padding-left:68px;color:#333;line-height:20px;}

.red_div{
	background-color: #FfF123;
}

.height28{
	height:28px;
}
.people_tbl{
	border-width: 0px;
	border-spacing: 5px;
	border-collapse: separate;
}
.people_tbl td{
	border-width: 1px;
	padding: 5px;
	border-style: solid;
	border-color: gray;
	//background-color: white;
	text-align:center;
	padding:5px;
	
}
.box{
	border: 1px solid rgba(0, 0, 0, 0.05);
    border-radius: 4px 4px 4px 4px;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0.05) inset;
    margin-bottom: 20px;
    min-height: 20px;
}

.box2{
	//border: 1px solid;
	border-color:#000000;
   	margin-bottom: 20px;
    min-height: 20px;
}

.box3{
	box-shadow:0pt 2px 4px rgba(0,0,0,0.2);		
}

#activity_list{
list-style: none outside none;
}
#activity_list p{
	width:100%;
	text-align:left;
	color:#0088CC;;
}

#gallery_div{
	margin-top:45px;
	margin-bottom:10px;
}
.people_label{
	padding-left:3px;
}

#main_container{
	margin-top:20px;
}
</style>
<link type="text/css" href="bootstrap/css/ui-lightness/jquery-ui-1.8.17.custom.css" rel="stylesheet" />
<link rel="stylesheet" href="css/slider/default/default.css" type="text/css" media="screen" />
<link rel="stylesheet" href="css/slider/pascal/pascal.css" type="text/css" media="screen" />
<link rel="stylesheet" href="css/slider/orman/orman.css" type="text/css" media="screen" />
<link type="text/css" href="bootstrap/css/bootstrap.css" rel="stylesheet" />
<link rel="stylesheet" href="css/slider/nivo-slider.css" type="text/css" media="screen" />
<link rel="stylesheet" href="css/slider/style.css" type="text/css" media="screen" />
<script type="text/javascript" src="js/jquery-1.7.1.min.js"></script>
<script type="text/javascript" src="js/jquery-ui-1.8.17.custom.min.js"></script>
<script type="text/javascript" src="bootstrap/js/bootstrap.js"></script>
<script type="text/javascript" src="js/calendar.js"></script>
<script type="text/javascript" src="js/jquery.nivo.slider.pack.js"></script>

</head>
<body>

<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<div class='row'>
		   		<div class='span8'>
		   		<a class="brand" href="#">
					<img src="images/logo3.png" width="120px" alt="DBAY TRIP"/>
				</a>
		        <ul class="nav">
			    <li class="active">
			    	<a href="#">首页</a>
			    </li>
			    <li><a href="#">搭车</a></li>
			    <li><a href="#">活动</a></li>
			    </ul>
			    </div>
			    <div class='span4'>
			    	<ul class="nav">
				    	<li><a href="/login">登陆</a></li>
				    	<li><a href="#">注册</a></li>
				    </ul>
			    </div>
			    </div>
			</div>
		</div>
</div>
<div class='container' id='main_container'>
<div class="row">
	<div class='row box' id='gallery_div'>
		<div class='span12'>
			<div class="row">
				<div class="span8">
					<div class="slider-wrapper theme-default">
			            <div id="slider" class="nivoSlider">
			                <img src="images/toystory.jpg" alt="" />
			                <a href="http://dev7studios.com"><img src="images/up.jpg" alt="" title="This is an example of a caption" /></a>
			                <img src="images/walle.jpg" alt="" data-transition="slideInLeft" />
			                <img src="images/nemo.jpg" alt="" title="#htmlcaption" />
			            </div>
            		</div>
				</div>
				<div class="span4 box3">Ranking</div>
				
			</div>
		</div>
	</div>
	
	<div class='row well'>
		<div class='span4'>
			<table class='people_tbl'>
			  <tbody>
			    <tr>
			      <td><img src="images/passenger-2.png"/><br/><input type='radio' name='people'/>乘客</td>
			      <td>
			      	<img src="images/attendee.png"/><br/>
			      	<input type='radio' name='people'/>&nbsp;参与者
			      </td>
			    </tr>
			    <tr>
			      <td><img src="images/driver.png"/><br/><input type='radio' name='people'/><label class='people_label'>司机</label></td>
			      <td><img src="images/planner.png"/><br/><input type='radio' name='people'/>策划者</td>
			    </tr>
			  </tbody>
			</table>
		
		</div>
		<div class='span4'>
			
			Image
		</div>
		<div class='span3'>
			<div class='span3'><input type="text" placeholder="起始日期..." class="height28" onclick="calendar.show(this);"></div>
			<div class='span3'><input type="text" placeholder="截止日期..." class="height28" onclick="calendar.show(this);"></div>
			<div class='span3'><input type="text" placeholder="地点..." class="height28"></div>
			<div class='span3'><a class="btn btn-large btn-primary" href="#">查询</a></div>
		</div>
	</div>
	<hr>
	<div class='row'>
		
		<div class='span7 box2'>
			<div class="wp">
				<ul id="slider" class="slider">
					<li><a class="fl" href="javascript:;"><img src="images/people.png" width="40px" height="40px" alt="" /></a>
					<p>入山又恐别倾城  世间安得双全 不负如来不负卿</p>
				    </li>
					<li><a class="fl" href="javascript:;"><img src="images/people.png" width="40px" height="40px"  alt="" /></a>
					<p>第一最好不相见，如此便可不相恋。</p>
					</li>
					<li><a class="fl" href="javascript:;"><img src="images/people.png" width="40px" height="40px"  alt="" /></a>
					<p>那一天 闭目在经殿香雾</p>
				    </li>
					<li><a class="fl" href="javascript:;"><img src="images/people.png" width="40px" height="40px"  alt="" /></a>
					<p> 你见 或者不见我  我就在那里 </p>
				</li>
				</ul>
			</div>
		</div>
		<div class='span5 box3'>
			<div class='row'>
				<dl>
					<dt>情人节</dt>
				</dl>
				<!-- 
				<ul id='activity_list'>
					<li>
						<p class='pull-left'>2月14日 情人节活动</p>
					</li>
					<li>
						<p class='pull-left'>2月14日 情人节活动</p>
					</li>
					<li>
						<p class='pull-left'>Napa 一日游活动</p>
					</li>
					 -->
				</ul>
			</div>
		</div>
		</div>
		
	</div>
</div>

<!--
<div class='outside_div'>
	<div class='inside_div' id='header'>	
		<div id='logo_div'>
			<a href=""><img src="images/logo1.jpg" /></a>
		</div>
		<div id='title_bar_div'>
			<ul class="nav-bar">
				<li><a id='renren_login' class="partner_login" href="#">人人登陆</a></li>
				<li><a class='nav_char' href="#">注册</a></li>
				<li><a class='nav_char' href="#">登陆</a></li>
			</ul>
		</div>
	</div>
</div>
<div class='outside_div'>
	<div class='inside_div box' id='main'>
		<div id='main_top'>
			<div class='float_left box_div' id='search_div'>
				<table>
					<tr>
						<td>起始:</<td><input type='text' id='from_date'></td>
						<td>截止:</<td><input type='text' id='to_date'></td>
						
					</tr>
				</table>
			</div>
			<div class='float_right' id='slide_image_div'>
				图片
			</div>
		</div>
		<div id='main_middle'>
			<input type='text' value='Search' id="search_box"/>
			<a class='link_btn'>信息查询</a>
		</div>
		<div id='main_bottom'>
			<div id='sepr_line'></div>
			<div class="wp">
				<ul id="slider" class="slider">
					<li><a class="fl" href="javascript:;"><img src="http://t1.qlogo.cn/mbloghead/b9127c4ca63961bace88/50" alt="" /></a>
					<p>入山又恐别倾城  世间安得双全 不负如来不负卿</p>
				    </li>
					<li><a class="fl" href="javascript:;"><img src="http://t1.qlogo.cn/mbloghead/b9127c4ca63961bace88/50" alt="" /></a>
					<p>第一最好不相见，如此便可不相恋。</p>
					</li>
					<li><a class="fl" href="javascript:;"><img src="http://t1.qlogo.cn/mbloghead/b9127c4ca63961bace88/50" alt="" /></a>
					<p>那一天 闭目在经殿香雾</p>
				    </li>
					<li><a class="fl" href="javascript:;"><img src="http://t1.qlogo.cn/mbloghead/b9127c4ca63961bace88/50" alt="" /></a>
					<p> 你见 或者不见我  我就在那里 </p>
				</li>
				</ul>
			</div>
			
		</div>
		
	</div>
</div>
<div class="outside_div">
	<div class='box' id='footer'>
		<ul class="nav-bar">
			<li>联系我们</li>
			<li>商务合作</li>
			<li>关注我们</li>
		</ul>
	</div>
</div>
-->
<script type="text/javascript">
//$(function() {
//	$( "#from_date" ).datepicker();
//	$( "#from_date" ).datepicker( "option", "dateFormat","yy-mm-dd");
//	$( "#to_date" ).datepicker();
//	$( "#to_date" ).datepicker( "option", "dateFormat","yy-mm-dd");
//});

$(function(){
msgmove(); 
$(".slider").hover(function(){
$(this).attr("name","hovered"); //鼠标经过设置ul的name值为"hovered"
},function(){
$(this).removeAttr("name");
});
});
function msgmove(){ var isIE=!!window.ActiveXObject;
var isIE6=isIE&&!window.XMLHttpRequest;
if($(".slider li").attr("name") != "hovered"){
//判断ul的name属性是否为"hovered"，决定下面代码块是否运行，以实现鼠标经过暂停滚动。
var height = $(".slider li:last").height();
if(isIE6){
//判断IE6，jQuery的animate动画和opacity透明在一起使用在IE6中会出现中文重影现象，
//所以在ie6中实行透明的禁用。
$(".slider li:last").css({"height":0});
}else{ $(".slider li:last").css({"opacity":0,"height":0});
//列表最后的li透明和高度设置为0 }
$(".slider li:first").before($(".slider li:last"));
//把列表最后的li提升到顶部，实现有限列表项无限循环滚动显示
$(".slider li:first").animate({"height":height},300);
//列表顶部的li高度逐渐变高以把下面的li推下去 if(!isIE6){
$(".slider li:first").animate({"opacity":"1"},300);
//在非IE6浏览器中设置透明淡入效果
}
}
setTimeout("msgmove()",3000);
//设置5秒滚动一次
}

$(window).load(function() {
    $('#slider').nivoSlider();
});
</script>
</body>
</html>