<div class='container' id='main_container'>
<div class="row box3">
	<div class="span6">
		<div class='row offset1 span5'>
				<form id='login_form'>
					<p class='h1'>登&nbsp;陆</p>
					<div class="dash-line"></div>
					<div class="control-group">
						<label for="login">账&#12288;号：</label>
						<div class="controls">
							<input id="username" name="username" class="height28 span3" placeholder="请输入昵称"type="text">
						</div>
					</div>
					<div class="control-group">
						<label for="passwd">密&#12288;码：</label>
						<div class="controls">
							<input id="passwd" name="passwd" class="height28 span3" placeholder="请输入密码" type="password">
						</div>
					</div>
					<div class="control-group">
						<div class="">
							<button class="btn btn-large btn-info">登&nbsp;陆</button>
						</div>
					</div>
				</form>
			
		</div>
		
	</div>
	<div class="span6">
		<div id='other_login'>
			<p>您可以用站外账号登录: </p><br/>
			<a href="http://www.meilishuo.com/connect/auth/renren" class="left reg_links"><img src="http://imgtest.meiliworks.com/css/images/connect/connect_rr.gif"></a>
		</div>
	</div>
</div>
</div>

<script type="text/javascript">
//$(function() {
//	$( "#from_date" ).datepicker();
//	$( "#from_date" ).datepicker( "option", "dateFormat","yy-mm-dd");
//	$( "#to_date" ).datepicker();
//	$( "#to_date" ).datepicker( "option", "dateFormat","yy-mm-dd");
//});

$(function(){
msgmove(); 
$(".slider").hover(function(){
$(this).attr("name","hovered"); //鼠标经过设置ul的name值为"hovered"
},function(){
$(this).removeAttr("name");
});
});
function msgmove(){ var isIE=!!window.ActiveXObject;
var isIE6=isIE&&!window.XMLHttpRequest;
if($(".slider li").attr("name") != "hovered"){
//判断ul的name属性是否为"hovered"，决定下面代码块是否运行，以实现鼠标经过暂停滚动。
var height = $(".slider li:last").height();
if(isIE6){
//判断IE6，jQuery的animate动画和opacity透明在一起使用在IE6中会出现中文重影现象，
//所以在ie6中实行透明的禁用。
$(".slider li:last").css({"height":0});
}else{ $(".slider li:last").css({"opacity":0,"height":0});
//列表最后的li透明和高度设置为0 }
$(".slider li:first").before($(".slider li:last"));
//把列表最后的li提升到顶部，实现有限列表项无限循环滚动显示
$(".slider li:first").animate({"height":height},300);
//列表顶部的li高度逐渐变高以把下面的li推下去 if(!isIE6){
$(".slider li:first").animate({"opacity":"1"},300);
//在非IE6浏览器中设置透明淡入效果
}
}
setTimeout("msgmove()",3000);
//设置5秒滚动一次
}

$(window).load(function() {
    $('#slider').nivoSlider();
});
</script>
</body>
</html>