<div class='container' id='main_container'>

<div class="row-fluid">
	<div class="span6">
		<div class='row-fluid box2'>
	 		<div class="div_head1"><p class='h2'>用户信息</p>
	 		</div>
	 		<div class="span3">
	 			<img class="user_profile_img" src="../images/user/user1.jpg"/>
	 		</div>
	 		<div class="span2">hello world</div>
	 	</div>
	</div>
	
	<div class="span6">
		<div class='row-fluid box2'>
	 	<div class="div_head1"><p class='h2'>自我推荐</p></div>
	 		<div class="span3">
	 		</div>
	 		<div class="span3">hello world</div>
	 	</div>
	</div>
	
</div>

<div class="row-fluid box2">
	 <div class="row-fluid">
	 <div class="div_head1"><p class='h2'>我的评价</p></div>
	 </div>
	 <div class="row-fluid">
	 
	 
	 <div class="span12">
	 <div class="left_border_div">
	 <ul class='unstyled'>
		 <li class="comment_div">
		 	<div class="row-fluid ">
		 		<div class="span2"><img alt="Profile Picture" src="http://graph.facebook.com/1342234563/picture?type=square"></div>
		 		<div class="span10">
		 			<div class="row-fluid ">
		 				<div class="span2">2012-02-28</div>
		 				<div class="offset1 span3">SanFranciso --> San Jose</div>
		 			</div>
		 			<div class="row-fluid">
		 				<div>姜师傅，姜师傅，姜师傅，姜师傅，姜师傅，</div>
		 			</div>
		 		</div>
		 	</div>
		 	
		 	
		 </li>
		 
		 <li class="comment_div">
		 	<div class="row-fluid ">
		 		<div class="span2"><img art="profile image" src="http://graph.facebook.com/591665618/picture?type=square" /></div>
		 		<div class="span10">
		 			<div class="row-fluid ">
		 				<div class="span2">2012-02-28</div>
		 				<div class="offset1 span3">SanFranciso --> San Jose</div>
		 			</div>
		 			<div class="row-fluid">
		 				<div>姜师傅，姜师傅，姜师傅，姜师傅，姜师傅，</div>
		 			</div>
		 		</div>
		 	</div>
		 	
		 	
		 </li>
		 
		 
		</ul>
		</div>
	 </div>
	</div>
</div>


</div>