<div class='container' id='main_container'>

<div class="row">
	<div class="span5 box2">
	 	<div class="div_head1"><p class='h2'>用户信息</p></div>
	 	
	 		<div class="span3">
	 			<img class="user_profile_img" src="../images/user/user1.jpg"/>
	 		</div>
	 		<div class="span2">hello world</div>
	 		
	 	
	</div>
	
	<div class="span7 box2">
	 	<div class="div_head1"><p class='h2'>自我推荐</p></div>
	 	
	 		<div class="span3">
	 			
	 		</div>
	 		<div class="span2">hello world</div>
	 		
	 	
	</div>
	
</div>

<div class="row">
	<div class="span12 box2">
	 <div class="div_head1"><p class='h2'>我的评价</p></div>
	 <div class="span3 right_border_div">
		  司机 / 组织者
	 </div>
	 <div class="span9">
	 <ul class="unstyled">
	 <li>
	 	<div class="row">
	 		<div class="span3">图像</div>
	 		<div class="span1">2012-02-28</div>
	 		<div class="offset2 span3">SanFranciso --> San Jose</div>
	 	</div>
	 	<div class="row comments">
	 		姜师傅行车安全， 言谈幽默风趣，希望能再次搭乘。。。 
	 	</div>
	 	
	 </li>
	 <li>
	 	<div class="row">
	 		<div class="span3">图像</div>
	 		<div class="span1">2012-02-28</div>
	 		<div class="offset2 span3">SanFranciso --> San Jose</div>
	 	</div>
	 	<div class="row comments">
	 		姜师傅行车安全， 言谈幽默风趣，希望能再次搭乘。。。 
	 	</div>
	 	
	 </li>
	 <li>
	 	<div class="row">
	 		<div class="span3">图像</div>
	 		<div class="span1">2012-02-28</div>
	 		<div class="offset2 span3">SanFranciso --> San Jose</div>
	 	</div>
	 	<div class="row comments">
	 		姜师傅行车安全， 言谈幽默风趣，希望能再次搭乘。。。 
	 	</div>
	 	
	 </li>
	 
	 </ul>
	 </div>
	</div>
</div>

	


</div>