<div class='container' id='main_container'>
<div class="row box3">
	<div class="span6">
		<div class='row offset1 span5'>
				<form id='login_form'>
					<p class='h1'>注册</p>
					<div class="dash-line"></div>
					<div class="control-group">
						<label for="login">账&#12288;号：</label>
						<div class="controls">
							<input id="username" name="username" class="height28 span3" placeholder="请输入昵称"type="text">
						</div>
					</div>
					<div class="control-group">
						<label for="email">账&#12288;号：</label>
						<div class="controls">
							<input id="email" name="email" class="height28 span3" placeholder="请输入电子邮箱"type="text">
						</div>
					</div>
					<div class="control-group">
						<label for="passwd">密&#12288;码：</label>
						<div class="controls">
							<input id="passwd" name="passwd" class="height28 span3" placeholder="请输入密码" type="password">
						</div>
					</div>
					<div class="control-group">
						<label for="passwd">再次输入密码：</label>
						<div class="controls">
							<input id="passwd2" name="passwd2" class="height28 span3" placeholder="请再次输入密码" type="password">
						</div>
					</div>
					<div class="control-group">
						<div class="">
							<button class="btn btn-large btn-info">注&nbsp;册</button>
						</div>
					</div>
				</form>
			
		</div>
		
	</div>
	<div class="span6">
		<div id='other_login'>
			<p>您可以用站外账号登录: </p><br/>
			<a href="http://www.meilishuo.com/connect/auth/renren" class="left reg_links"><img src="http://imgtest.meiliworks.com/css/images/connect/connect_rr.gif"></a>
		</div>
	</div>
</div>
</div>
